# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI Tests

on:
  push:
    branches: [ "main", "release", "ci-dev" ]
  pull_request:
    branches: [ "main", "release", "ci-dev" ]

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      build_configuration: ${{ steps.set_buildconfig.outputs.build_configuration }}
    steps:
      - name: Set release configuration for release branches
        id: set_buildconfig
        run: |
          if [[ "${{github.base_ref}}" == "release" ]]; then
            echo "::set-output name=build_configuration::release"
          else
            echo "::set-output name=build_configuration::debug"
          fi

  build_test:
    uses: ./.github/workflows/build_test.yml
    needs: init
    with:
      test_args: --filter TestCategory!="Compatibility"
      build_configuration: ${{ needs.init.outputs.build_configuration }}
      store_artifacts: true
  build_test_backward_compatibility:
    uses: ./.github/workflows/build_test.yml
    needs: init
    with:
      environment: "MC Integration"
      test_args: --filter TestCategory="Compatibility"
      build_configuration: ${{ needs.init.outputs.build_configuration }}